---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.6

Style/HashSyntax:
  EnforcedShorthandSyntax: never # for ruby 3.0 support

Metrics/ParameterLists:
  Enabled: False

RSpec/ExampleLength:
  Enabled: False

RSpec/MultipleMemoizedHelpers:
   Max: 10

Naming/FileName:
  Exclude:
    - guide/Rules

# see https://github.com/rubocop/ruby-style-guide/issues/329
# I am team "if not" (when it makes sense)
Style/NegatedIf:
  Enabled: false
