---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/HashSyntax:
  EnforcedShorthandSyntax: never # for ruby 3.0 support

Metrics/ParameterLists:
  Enabled: False
